### ISSUE TITLE
Issue running

### ISSUE THREAD

**Issue by AlphonsoJuice** [danked-sb/danked#18]
ok so I am a complete noob (pls no hate). whenever I try to run it, it says danked and detected user thing, but it never runs on the account. Can you tell what I did wrong (or maybe give instructions on how to use it properly). I would be obliged if you would help me

**Comment by 1x6** [comment]
sorry, I didn't really give instructions at all, I'll add some to the readme. 
Basically, when you have configured it to your liking, send `.danked start` in a server on the account you're farming on. It will print some stuff and then it will start farming. btw, **make sure the account has been used for a bit** before using danked for **over 1h 30m** per day because otherwise you will get a blacklist. after the blacklist is over, though, the account works fine with danked for about 3h

**Comment by Acqtn** [comment]
> ok so I am a complete noob (pls no hate). whenever I try to run it, it says danked and detected user thing, but it never runs on the account. Can you tell what I did wrong (or maybe give instructions on how to use it properly). I would be obliged if you would help me

You're so sexy.

**Comment by danked-helper** [comment]
ur so fucking hawt <3 @AlphonsoJuice

**Comment by danked-helper** [comment]
@AlphonsoJuice Ilysm
👍🏿

**Comment by danked-helper** [comment]
@AlphonsoJuice Ilysm
👍🏿

**Comment by danked-helper** [comment]
@AlphonsoJuice Ilysm
👍🏿

**Comment by danked-helper** [comment]
@AlphonsoJuice Ilysm
👍🏿

**Comment by danked-helper** [comment]
@AlphonsoJuice add xeny#2808

**Comment by danked-helper** [comment]
@AlphonsoJuice add xeny#2808

**Comment by danked-helper** [comment]
@AlphonsoJuice add xeny#2808

**Comment by danked-helper** [comment]
@AlphonsoJuice add xeny#2808

**Comment by danked-helper** [comment]
@AlphonsoJuice add xeny#2808

**Comment by Acqtn** [comment]
@AlphonsoJuice add me on discord: Dank#4128 we can do some stuffs together 😍 ❤️

**Comment by Acqtn** [comment]
@AlphonsoJuice add me on discord: Dank#4128 we can do some stuffs together 😍 ❤️

**Comment by Acqtn** [comment]
@AlphonsoJuice add me on discord: Dank#4128 we can do some stuffs together 😍 ❤️

**Comment by Acqtn** [comment]
@AlphonsoJuice add me on discord: Dank#4128 we can do some stuffs together 😍 ❤️

**Comment by Acqtn** [comment]
@AlphonsoJuice add me on discord: Dank#4128 we can do some stuffs together 😍 ❤️

**Comment by Acqtn** [comment]
@AlphonsoJuice add me on discord: Dank#4128 we can do some stuffs together 😍 ❤️

**Comment by Acqtn** [comment]
@AlphonsoJuice add me on discord: Dank#4128 we can do some stuffs together 😍 ❤️

**Comment by Acqtn** [comment]
@AlphonsoJuice add me on discord: Dank#4128 we can do some stuffs together 😍 ❤️

**Comment by Acqtn** [comment]
@AlphonsoJuice add me on discord: Dank#4128 we can do some stuffs together 😍 ❤️

**Comment by Acqtn** [comment]
@AlphonsoJuice add me on discord: Dank#4128 we can do some stuffs together 😍 ❤️

**Comment by Acqtn** [comment]
@AlphonsoJuice add me on discord: Dank#4128 we can do some stuffs together 😍 ❤️

**Comment by Acqtn** [comment]
@AlphonsoJuice add me on discord: Dank#4128 we can do some stuffs together 😍 ❤️

**Comment by danked-helper** [comment]
@acqtn keep goong

**Comment by Acqtn** [comment]
@AlphonsoJuice add me on discord: Dank#4128 we can do some stuffs together 😍 ❤️

**Comment by Acqtn** [comment]
@AlphonsoJuice add me on discord: Dank#4128 we can do some stuffs together 😍 ❤️

**Comment by Acqtn** [comment]
@AlphonsoJuice add me on discord: Dank#4128 we can do some stuffs together 😍 ❤️

**Comment by Acqtn** [comment]
> @Acqtn keep goong

yes sir captain sir



@AlphonsoJuice add me on discord: Dank#4128 we can do some stuffs together 😍 ❤️

**Comment by Acqtn** [comment]
@AlphonsoJuice add me on discord: Dank#4128 we can do some stuffs together 😍 ❤️

**Comment by Acqtn** [comment]
@AlphonsoJuice add me on discord: Dank#4128 we can do some stuffs together 😍 ❤️

**Comment by Acqtn** [comment]
@AlphonsoJuice add me on discord: Dank#4128 we can do some stuffs together 😍 ❤️
